version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/sites:/etc/nginx/conf.d
      - ./html:/var/www/html
    networks: 
      - dev
    links:
      - "php7.4-fpm"
  php7.4-fpm:
    build: ./php/7.4
    ports:
      - 9074:9000
    networks: 
      - dev
    volumes:
      - ./html:/var/www/html
    links:
      - mysql
  php8.0-fpm:
    build: ./php/8.0
    ports:
      - 9080:9000
    networks: 
      - dev
    volumes:
      - ./html:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks: 
      - dev

networks:
  dev:
    driver: bridge